### ISSUE TITLE
History Map - Create logic

### ISSUE THREAD

**Issue by OlhaPivniuk** [project-studying-dotnet/Streetcode-Admin-March-01#163]
[User story](https://github.com/project-studying-dotnet/Streetcode-Admin-March-01/issues/52)

### **Task** - Implement Create logic for History Map

Create DTO 
Create mediator command
Create mediator handler 
Add validator
Create POST method Create in Controller
Write tests for Handler and Validator

- _use StatisticRecord Entity_

### **Details** 
Admin can add records about the location of physical street code:
-can be added via a dropdown
-can be added via a selection of specific locations on a map
Number of physical street code should be unique per one street code image

**Comment by HlibBondarev** [comment]
Development tasks

1. Add get-property PhisicalStreetcode to StreetcodeToponym.
Apply attribute - [NotMapped] in order not to store this property in the table streetcode_toponym.
This is redundant because EF also doesn't create a column for a property that doesn't have at least one of its method - Get or Set.

2. Create DTO:
2.1. CreateStreetcodeToponymRequestDto should contain: StreetcodeId and ToponymId;
2.2. CreateStreetcodeToponymResponseDto;

3. Create Mediator Handler - 
CreateStreetcodeToponymHandler and CreateStreetcodeToponymCommand

4. Create Endpoints - 
Create - which would receive CreateStreetcodeToponymRequestDto and then - create StreetcodeToponym entitie.

5. Create Tests for handlers -
CreateStreetcodeToponymHandler tests

6. Create Tests for FluentValidation for FluentValidator - 
CreateStreetcodeToponymRequestDtoValidator
